
server:
  port: 10000
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

# Spring配置
spring:
  profiles:
    # 生效配置文件
    active: dev
  # Cache 配置
  cache:
    type: redis
    redis:
      #缓存超时时间ms
      time-to-live: 5000ms
      #是否缓存空值
      cache-null-values: false
  # Redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 100
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # freemarker配置
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    charset: UTF-8
    settings:
      default-encoding: UTF-8
  # Jackson配置
  jackson:
    # 指定日期格式化时区，比如America/Los_Angeles或者GMT+10
    time-zone: GMT+8
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    # 序列化配置
    serialization:
      # 格式化输出
      indent_output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: false
      write-dates-as-timestamps: true
    # 设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    # 反序列化
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      # 允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      # 允许出现单引号
      allow_single_quotes: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: classpath:/bundle/messages
    default-encoding: UTF-8
    cache-seconds: 0
    use-code-as-default-message: false
  # 文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true


# 日志配置
logging:
  level:
    org.spring.springboot.dao: debug

